// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/mobile_phone.dart';
import 'models/person.dart';
import 'models/person2.dart';
import 'models/person3.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7372432614047728194),
      name: 'Person',
      lastPropertyId: const IdUid(2, 7758185630413673747),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5996101597028580650),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7758185630413673747),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 3317564504393514481),
      name: 'Person2',
      lastPropertyId: const IdUid(4, 4094973733591322570),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3135051302578002),
            name: 'personId',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5112210807216445125),
            name: 'nationalIdNumber',
            type: 9,
            flags: 2080,
            indexId: const IdUid(1, 5473758415654850545)),
        ModelProperty(
            id: const IdUid(3, 6039689840133272955),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4094973733591322570),
            name: 'age',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 8232796582027321161),
      name: 'MobilePhone',
      lastPropertyId: const IdUid(3, 1720466795555456746),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8718851139220232281),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8145633037981347324),
            name: 'modelName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 1720466795555456746),
            name: 'ownerId',
            type: 11,
            flags: 520,
            indexId: const IdUid(2, 5483346364824129990),
            relationTarget: 'Person3')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(5, 1383395875485676893),
      name: 'Person3',
      lastPropertyId: const IdUid(2, 8193505378004416885),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8128050668334027415),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8193505378004416885),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[
        ModelBacklink(
            name: 'phones', srcEntity: 'MobilePhone', srcField: 'owner')
      ])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(5, 1383395875485676893),
      lastIndexId: const IdUid(2, 5483346364824129990),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [2965186645711582199],
      retiredIndexUids: const [],
      retiredPropertyUids: const [3543580690058663064, 5176975212773299051],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Person: EntityDefinition<Person>(
        model: _entities[0],
        toOneRelations: (Person object) => [],
        toManyRelations: (Person object) => {},
        getId: (Person object) => object.id,
        setId: (Person object, int id) {
          object.id = id;
        },
        objectToFB: (Person object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Person(
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));

          return object;
        }),
    Person2: EntityDefinition<Person2>(
        model: _entities[1],
        toOneRelations: (Person2 object) => [],
        toManyRelations: (Person2 object) => {},
        getId: (Person2 object) => object.personId,
        setId: (Person2 object, int id) {
          object.personId = id;
        },
        objectToFB: (Person2 object, fb.Builder fbb) {
          final nationalIdNumberOffset =
              fbb.writeString(object.nationalIdNumber);
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(5);
          fbb.addInt64(0, object.personId);
          fbb.addOffset(1, nationalIdNumberOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addInt64(3, object.age);
          fbb.finish(fbb.endTable());
          return object.personId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Person2(
              personId:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              nationalIdNumber: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              age: const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));

          return object;
        }),
    MobilePhone: EntityDefinition<MobilePhone>(
        model: _entities[2],
        toOneRelations: (MobilePhone object) => [object.owner],
        toManyRelations: (MobilePhone object) => {},
        getId: (MobilePhone object) => object.id,
        setId: (MobilePhone object, int id) {
          object.id = id;
        },
        objectToFB: (MobilePhone object, fb.Builder fbb) {
          final modelNameOffset = fbb.writeString(object.modelName);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, modelNameOffset);
          fbb.addInt64(2, object.owner.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = MobilePhone(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              modelName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''));
          object.owner.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.owner.attach(store);
          return object;
        }),
    Person3: EntityDefinition<Person3>(
        model: _entities[3],
        toOneRelations: (Person3 object) => [],
        toManyRelations: (Person3 object) => {
              RelInfo<MobilePhone>.toOneBacklink(
                      3, object.id, (MobilePhone srcObject) => srcObject.owner):
                  object.phones
            },
        getId: (Person3 object) => object.id,
        setId: (Person3 object, int id) {
          object.id = id;
        },
        objectToFB: (Person3 object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Person3(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''));
          InternalToManyAccess.setRelInfo<Person3>(
              object.phones,
              store,
              RelInfo<MobilePhone>.toOneBacklink(
                  3, object.id, (MobilePhone srcObject) => srcObject.owner));
          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Person] entity fields to define ObjectBox queries.
class Person_ {
  /// see [Person.id]
  static final id = QueryIntegerProperty<Person>(_entities[0].properties[0]);

  /// see [Person.name]
  static final name = QueryStringProperty<Person>(_entities[0].properties[1]);
}

/// [Person2] entity fields to define ObjectBox queries.
class Person2_ {
  /// see [Person2.personId]
  static final personId =
      QueryIntegerProperty<Person2>(_entities[1].properties[0]);

  /// see [Person2.nationalIdNumber]
  static final nationalIdNumber =
      QueryStringProperty<Person2>(_entities[1].properties[1]);

  /// see [Person2.name]
  static final name = QueryStringProperty<Person2>(_entities[1].properties[2]);

  /// see [Person2.age]
  static final age = QueryIntegerProperty<Person2>(_entities[1].properties[3]);
}

/// [MobilePhone] entity fields to define ObjectBox queries.
class MobilePhone_ {
  /// see [MobilePhone.id]
  static final id =
      QueryIntegerProperty<MobilePhone>(_entities[2].properties[0]);

  /// see [MobilePhone.modelName]
  static final modelName =
      QueryStringProperty<MobilePhone>(_entities[2].properties[1]);

  /// see [MobilePhone.owner]
  static final owner =
      QueryRelationToOne<MobilePhone, Person3>(_entities[2].properties[2]);
}

/// [Person3] entity fields to define ObjectBox queries.
class Person3_ {
  /// see [Person3.id]
  static final id = QueryIntegerProperty<Person3>(_entities[3].properties[0]);

  /// see [Person3.name]
  static final name = QueryStringProperty<Person3>(_entities[3].properties[1]);
}
